# Stage 1 - Filter raw data for GB companies and persons
ownership_data_raw: data/raw/statements.latest.jsonl

companies_interim: data/interim/companies.parquet
relationships_interim: data/interim/relationships.parquet
persons_interim: data/interim/persons.parquet
addresses_interim: data/interim/addresses.parquet

# Stage 2 - Select and create relevant columns
companies_processed: data/processed/companies.parquet
relationships_processed: data/processed/relationships.parquet
persons_processed: data/processed/persons.parquet
addresses_processed: data/processed/addresses.parquet
